apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: buildah-vol
      persistentVolumeClaim:
        claimName: buildah-volume
#    - name: workspace-volume
#      persistentVolumeClaim:
#        claimName: agent-workspace
  containers:
#  - name: jnlp
#    image: jenkins/inbound-agent:latest
#    volumeMounts:
#        - mountPath: "/home/jenkins/agent"
#          name: workspace-volume
  - name: buildah
    image: quay.io/buildah/stable:latest
    securityContext:
       capabilities:
         add:
           - "SYS_ADMIN"
           - "MKNOD"
           - "SYS_CHROOT"
           - "SETFCAP"
    resources:
          limits:
            smarter-devices/fuse: 1
          requests:
            smarter-devices/fuse: 1
    volumeMounts:
        - mountPath: "/var/lib/containers:Z"
          name: buildah-vol
    command:
    - sleep
    args:
    - 99d