apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: agent-workspace
      persistentVolumeClaim:
        claimName: agent-workspace
    - name: node-npm
      persistentVolumeClaim:
        claimName: node-npm
    - name: buildah-volume
      persistentVolumeClaim:
        claimName: buildah-volume
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: agent-workspace
  - name: node
    image: node:latest
    volumeMounts:
        - mountPath: "/root/.npm"
          name: node-npm
    command:
    - sleep
    args:
    - 99d
  - name: buildah
    image: quay.io/buildah/stable:latest
    volumeMounts:
        - mountPath: "/var/lib/containers:Z"
          name: buildah-volume
    command:
    - sleep
    args:
    - 99d