apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: buildah-vol
      persistentVolumeClaim:
        claimName: buildah-volume
    - name: jenkins-vol
      persistentVolumeClaim:
        claimName: agent-workspace
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: jenkins-vol
  - name: buildah
    image: quay.io/buildah/stable:latest
    securityContext:
       capabilities:
         add:
           - "SYS_ADMIN"
           - "MKNOD"
           - "SYS_CHROOT"
           - "SETFCAP"
    volumeMounts:
        - mountPath: "/var/lib/containers:Z"
          name: buildah-vol
    command:
    - sleep
    args:
    - 99d