apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: workspace-volume
      persistentVolumeClaim:
        claimName: agent-workspace
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
    volumeMounts:
        - mountPath: "/home/jenkins/agent"
          name: workspace-volume
  - name: node
    image: node:latest
    command:
    - sleep
    args:
    - 99d
  - name: buildah
    image: quay.io/buildah/stable:latest
    command:
    - sleep
    args:
    - 99d