apiVersion: v1
kind: Pod

spec:
  volumes:
    - name: buildah-vol
      persistentVolumeClaim:
        claimName: buildah-volume
    - name: node-vol
      persistentVolumeClaim:
        claimName: node-npm
    
  containers:

  - name: node
    image: node:latest
    volumeMounts:
        - mountPath: "/root/.npm"
          name: node-vol
    command:
    - sleep
    args:
    - 99d


  - name: buildah
    image: docker.io/younesic/buildah
    securityContext:
    
    volumeMounts:
        - mountPath: "/home/build/.local/share/containers"
          name: buildah-vol
    command:
    - python3
    args:
    - -m
    - http.server
  - name: skopeo
    image: docker.io/younesic/skopeo
    env:
       -  name: DOCKER_USR
          value: younesic
       -  name: DOCKER_PWD
          value: Dh123581321*
    securityContext:
    volumeMounts:
        - mountPath: "/home/skopeo/.local/share/containers"
          name: buildah-vol
    command:
    - sleep
    args:
    - 99d

  





