apiVersion: v1
kind: Pod
metadata: 
  annotations: 
      container.apparmor.security.beta.kubernetes.io/buildah: unconfined
      container.apparmor.security.beta.kubernetes.io/skopeo: unconfined
spec:
  volumes:
    - name: buildah-vol
      persistentVolumeClaim:
        claimName: buildah-volume
#    - name: workspace-volume
#      persistentVolumeClaim:
#        claimName: agent-workspace
  containers:
#  - name: jnlp
#    image: jenkins/inbound-agent:latest
#    volumeMounts:
#        - mountPath: "/home/jenkins/agent"
#          name: workspace-volume
  - name: buildah
    image: quay.io/buildah/stable:latest
    securityContext:
     #  capabilities:
     #    add: ["CAP_SYS_ADMIN"]
       seLinuxOptions:
         level: disable
       

    resources:
          limits:
            smarter-devices/fuse: 1
          requests:
            smarter-devices/fuse: 1
    volumeMounts:
        - mountPath: "/var/lib/containers:Z"
          name: buildah-vol
    command:
    - sleep
    args:
    - 99d
  - name: skopeo
    image: quay.io/skopeo/stable:latest
    env:
       -  name: DOCKER_USR
          value: younesic
       -  name: DOCKER_PWD
          value: Dh123581321*
    securityContext:
     #  capabilities:
     #    add: ["CAP_SYS_ADMIN"]
       seLinuxOptions:
         level: disable
    resources:
          limits:
            smarter-devices/fuse: 1
          requests:
            smarter-devices/fuse: 1
    volumeMounts:
        - mountPath: "/var/lib/containers:Z"
          name: buildah-vol
    command:
    - sleep
    args:
    - 99d






