apiVersion: v1
kind: Pod
metadata: 
#  annotations: 
#      container.apparmor.security.beta.kubernetes.io/buildah: unconfined
#      container.apparmor.security.beta.kubernetes.io/skopeo: unconfined
spec:
  volumes:
    - name: buildah-vol
      persistentVolumeClaim:
        claimName: buildah-volume
    

  containers:

  - name: buildah
    image: docker.io/younesic/buildah
    securityContext:
    #    runAsUser: 1000
    #    runAsGroup: 1000
        capabilities:
          add: 
            - SETUID
            - SETGID
#        seLinuxOptions:
#         level: disable
#    resources:
#          limits:
#            smarter-devices/fuse: 1
#          requests:
#            smarter-devices/fuse: 1
    volumeMounts:
        - mountPath: "/var/lib/containers:Z"
          name: buildah-vol
    command:
    - python3
    args:
    - -m
    - http.server
  - name: skopeo
    image: quay.io/skopeo/stable:latest
    env:
       -  name: DOCKER_USR
          value: younesic
       -  name: DOCKER_PWD
          value: Dh123581321*
    securityContext:
    #    runAsUser: 1000
    #    runAsGroup: 1000
    #   capabilities:
    #     add: ["CAP_SYS_ADMIN"]
    #  seLinuxOptions:
    #     level: disable
    #resources:
    #      limits:
    #        smarter-devices/fuse: 1
    #      requests:
    #        smarter-devices/fuse: 1
    volumeMounts:
        - mountPath: "/home/skopeo/mycontainers:Z"
          name: buildah-vol
    command:
    - sleep
    args:
    - 99d






