apiVersion: v1
kind: Pod
spec:
  volumes:
    - name: buildah-vol
      persistentVolumeClaim:
        claimName: buildah-volume
#    - name: workspace-volume
#      persistentVolumeClaim:
#        claimName: agent-workspace
  containers:
#  - name: jnlp
#    image: jenkins/inbound-agent:latest
#    volumeMounts:
#        - mountPath: "/home/jenkins/agent"
#          name: workspace-volume
  - name: buildah
    image: quay.io/buildah/stable:latest
    securityContext:
       capabilities:
         add: [CHOWN,DAC_OVERRIDE,DAC_READ_SEARCH,FOWNER,FSETID,KILL,SETGID,SETUID,SETPCAP,LINUX_IMMUTABLE,NET_BIND_SERVICE,NET_BROADCAST,NET_ADMIN,NET_RAW,IPC_LOCK,IPC_OWNER,SYS_MODULE,SYS_RAWIO,SYS_CHROOT,SYS_PTRACE,SYS_PACCT,SYS_ADMIN,SYS_BOOT,SYS_NICE,SYS_RESOURCE,SYS_TIME,SYS_TTY_CONFIG,MKNOD,LEASE,AUDIT_WRITE,AUDIT_CONTROL,SETFCAP,MAC_OVERRIDE,MAC_ADMIN,SYSLOG,WAKE_ALARM,BLOCK_SUSPEND,AUDIT_READ]
    resources:
          limits:
            smarter-devices/fuse: 1
          requests:
            smarter-devices/fuse: 1
    volumeMounts:
        - mountPath: "/var/lib/containers:Z"
          name: buildah-vol
    command:
    - sleep
    args:
    - 99d