apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest
  - name: node
    image: node:latest
    command:
    - sleep
    args:
    - 99d
  - name: buildah
    image: quay.io/buildah/stable:latest
    command:
    - sleep
    args:
    - 99d