apiVersion: v1
kind: Pod
metadata: 
#  annotations: 
#      container.apparmor.security.beta.kubernetes.io/buildah: unconfined
#      container.apparmor.security.beta.kubernetes.io/skopeo: unconfined
spec:
  volumes:
    - name: buildah-vol
      persistentVolumeClaim:
        claimName: buildah-volume
    

  containers:

  - name: buildah
    image: docker.io/younesic/buildah
    securityContext:
    #    runAsUser: 1000
    #    runAsGroup: 1000
    #    capabilities:
    #      add: 
    #        - SETUID
    #        - SETGID
#        seLinuxOptions:
#         level: disable
#    resources:
#          limits:
#            smarter-devices/fuse: 1
#          requests:
#            smarter-devices/fuse: 1
    volumeMounts:
        - mountPath: "/home/skopeo/.local/share/containers"
          name: buildah-vol
    command:
    - python3
    args:
    - -m
    - http.server
  - name: skopeo
    image: docker.io/younesic/skopeo
    env:
       -  name: DOCKER_USR
          value: younesic
       -  name: DOCKER_PWD
          value: Dh123581321*
    securityContext:
    #     runAsUser: 1000
    #     runAsGroup: 1000
        capabilities:
          add: ["SYS_CHROOT"]
    #  seLinuxOptions:
    #     level: disable
    #resources:
    #      limits:
    #        smarter-devices/fuse: 1
    #      requests:
    #        smarter-devices/fuse: 1
    volumeMounts:
        - mountPath: "/home/skopeo/.local/share/containers"
          name: buildah-vol
    command:
    - python3
    args:
    - -m
    - http.server






