podTemplate(containers: [



        containerTemplate(
        name: 'jnlp', 
        image: 'jenkins/inbound-agent:latest'
        ),
    containerTemplate(
        name: 'node', 
        image: 'node:latest', 
        command: 'sleep', 
        args: '30d')
  ],
  volumes: [
  persistentVolumeClaim(
      mountPath: '/home/jenkins/agent', 
      claimName: 'agent-workspace'      ),
  persistentVolumeClaim(
      mountPath: '/root/.npm', 
      claimName: 'node-npm'      )
  ]
  
  ) {
node('CI-POD') {
    environment {
            CI = 'true'
                }
    stage ('Git'){
            git url: 'https://github.com/younes-bami/node.git', branch: 'master'
    }
    stage ('Build'){
            container('node'){
			            sh """
                  cd \${PWD}
			            npm install
                  npm run build
                  """
                             }

    }
    stage('Test ') {                        
           container('node'){
                        sh """
                         ./jenkins/scripts/test.sh
                           """
                             }
    }

      


}
  }
podTemplate(yaml: readTrusted('pod.yaml')) {

  node('CD_POD') {
  environment {
      CI = 'true'
                }
 //when { environment name: 'DEPLOY_TO', value: 'production' } 
 //          env.BRANCH_NAME != 'master';
     
 stage('Artefact ') {    
            when (branch 'prod')
            steps(){
            container('buildah'){
 
                            git url: 'https://github.com/younes-bami/node.git', branch: 'master'
                            sh """
                            cd \${PWD}
                            buildah build --layers=true  -t web-app:latest .
                            buildah images --all
                            """ 

                             }
      
          container('skopeo'){
                          sh """
                          cd /home/skopeo
                          skopeo inspect containers-storage:localhost/web-app:latest 
                          skopeo copy --dest-creds \${DOCKER_USR}:\${DOCKER_PWD} containers-storage:localhost/web-app:latest docker://docker.io/younesic/web-app 
                          """

    
    }
 }  
    }
}
}
