podTemplate(containers: [

        containerTemplate(
        name: 'jnlp', 
        image: 'jenkins/inbound-agent:latest'
        ),
    containerTemplate(
        name: 'node', 
        image: 'node:latest', 
        command: 'sleep', 
        args: '30d')
  ],
  volumes: [
  persistentVolumeClaim(
      mountPath: '/home/jenkins/agent', 
      claimName: 'maven-workspace'      ),
  persistentVolumeClaim(
      mountPath: '/root/.npm', 
      claimName: 'node-npm'      )
  ]
  
  ) {
node(POD_LABEL) {
    environment {
            CI = 'true'
                }
    stage ('Git Stage'){
            git url: 'https://github.com/younes-bami/node.git', branch: 'master'
    }
    stage ('build Stage'){
            container('node'){
                  stage('build'){
			            sh '''
			            npm install
			            '''		             }
                             }

    }
    stage('Test Stage') {                        
           container('node'){
                  stage('Test'){
                        sh '''
                         ./jenkins/scripts/test.sh
                           '''
                               }
                             }
    }

    stage ('Deliver Stage'){
           container('node'){
                  stage('deliver'){
                        sh '''
                         ./jenkins/scripts/deliver.sh
                           '''
                           
                         input message: 'Finished using the web site? (Click "Proceed" to continue)'

                         sh '''
                         ./jenkins/scripts/kill.sh
                           '''
                               }
                             }

}

}

}
