podTemplate(yaml: readTrusted('pod.yaml')) {

  node(POD_LABEL) {
  environment {
      CI = 'true'
                }
  stage ('Git'){
            git url: 'https://github.com/younes-bami/node.git', branch: 'feature/Two-pods-jenkinsfile'
    }
    stage ('Build'){
            container('node'){
			            sh """
                  cd \${PWD}
			            npm install
                  npm run build
                  """
                             }

    }
    stage('Test ') {                        
           container('node'){
                        sh """
                         ./jenkins/scripts/test.sh
                           """
                             }
    }


}


}

